-- =============================================
-- STAFF SCHEDULER — DATABASE SCHEMA
-- Run this in your Supabase SQL editor
-- =============================================


-- =============================================
-- CORE USER MANAGEMENT
-- =============================================

create table staff_profiles (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid references auth.users(id) on delete cascade not null unique,
  full_name     text not null,
  email         text not null,
  phone         text,
  role          text not null default 'staff' check (role in ('staff', 'admin')),
  priority_rank int default 5 check (priority_rank between 1 and 10),
  notify_email  boolean default true,
  notify_sms    boolean default false,
  is_active     boolean default true,
  created_at    timestamptz default now()
);

-- Auto-create staff_profiles when a new user signs up via invite
create or replace function handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.staff_profiles (user_id, full_name, email, role, priority_rank)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.email,
    coalesce(new.raw_user_meta_data ->> 'role', 'staff'),
    coalesce((new.raw_user_meta_data ->> 'priority_rank')::int, 5)
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure handle_new_user();


-- Invite tokens generated by admin to onboard new staff
create table invitations (
  id          uuid primary key default gen_random_uuid(),
  email       text not null,
  token       text not null unique default gen_random_uuid()::text,
  role        text not null default 'staff' check (role in ('staff', 'admin')),
  invited_by  uuid references staff_profiles(id),
  accepted_at timestamptz,
  expires_at  timestamptz not null default (now() + interval '7 days'),
  created_at  timestamptz default now()
);


-- =============================================
-- EMPLOYEE AVAILABILITY
-- =============================================

-- Standing weekly pattern — persists month to month, set once in profile
create table weekly_availability (
  id             uuid primary key default gen_random_uuid(),
  staff_id       uuid references staff_profiles(id) on delete cascade not null,
  day_of_week    int not null check (day_of_week between 0 and 6), -- 0=Sun, 6=Sat
  available_from time not null,
  available_to   time not null,
  updated_at     timestamptz default now(),
  unique(staff_id, day_of_week)
);

-- One submission record per staff member per month
create table availability_submissions (
  id                       uuid primary key default gen_random_uuid(),
  staff_id                 uuid references staff_profiles(id) on delete cascade not null,
  month                    int not null check (month between 1 and 12),
  year                     int not null,
  preferred_shifts_per_week int check (preferred_shifts_per_week > 0),
  is_submitted             boolean default false,
  submitted_at             timestamptz,
  created_at               timestamptz default now(),
  unique(staff_id, month, year)
);

-- Per-day availability within a monthly submission
create table availability_days (
  id             uuid primary key default gen_random_uuid(),
  submission_id  uuid references availability_submissions(id) on delete cascade not null,
  date           date not null,
  available_from time,
  available_to   time,
  is_unavailable boolean default false,
  unique(submission_id, date)
);

-- Time-off requests (separate from availability — require manager approval)
create table time_off_requests (
  id          uuid primary key default gen_random_uuid(),
  staff_id    uuid references staff_profiles(id) on delete cascade not null,
  date        date not null,
  reason      text,
  status      text not null default 'pending' check (status in ('pending', 'approved', 'denied')),
  reviewed_by uuid references staff_profiles(id),
  reviewed_at timestamptz,
  created_at  timestamptz default now()
);


-- =============================================
-- MANAGER / SCHEDULING SETUP
-- =============================================

-- One config per calendar month — tracks status through the workflow
create table monthly_configs (
  id          uuid primary key default gen_random_uuid(),
  month       int not null check (month between 1 and 12),
  year        int not null,
  status      text not null default 'draft'
                check (status in ('draft', 'pending_approval', 'approved', 'published')),
  notes       text,
  created_by  uuid references staff_profiles(id),
  approved_by uuid references staff_profiles(id),
  approved_at timestamptz,
  published_at timestamptz,
  created_at  timestamptz default now(),
  unique(month, year)
);

-- Default shifts per day-of-week for a month config
create table weekly_shift_templates (
  id                uuid primary key default gen_random_uuid(),
  monthly_config_id uuid references monthly_configs(id) on delete cascade not null,
  day_of_week       int not null check (day_of_week between 0 and 6),
  is_closed         boolean default false,
  unique(monthly_config_id, day_of_week)
);

-- Individual shift slots within a weekly template
create table template_shifts (
  id                 uuid primary key default gen_random_uuid(),
  weekly_template_id uuid references weekly_shift_templates(id) on delete cascade not null,
  start_time         time not null,
  end_time           time not null,
  slots_needed       int not null default 1 check (slots_needed > 0)
);

-- Date-specific overrides — replace the weekly template for a given date
create table date_shift_overrides (
  id                uuid primary key default gen_random_uuid(),
  monthly_config_id uuid references monthly_configs(id) on delete cascade not null,
  date              date not null,
  is_closed         boolean default false,
  unique(monthly_config_id, date)
);

-- Individual shift slots within a date override
create table override_shifts (
  id          uuid primary key default gen_random_uuid(),
  override_id uuid references date_shift_overrides(id) on delete cascade not null,
  start_time  time not null,
  end_time    time not null,
  slots_needed int not null default 1 check (slots_needed > 0)
);

-- Manager-set min/max shifts per staff member (null monthly_config_id = global default)
create table staff_scheduling_rules (
  id                uuid primary key default gen_random_uuid(),
  staff_id          uuid references staff_profiles(id) on delete cascade not null,
  monthly_config_id uuid references monthly_configs(id) on delete cascade,
  min_shifts_per_week int default 0,
  max_shifts_per_week int,
  created_at        timestamptz default now(),
  unique(staff_id, monthly_config_id)
);

-- Staff pairs that shouldn't be scheduled together
create table staff_incompatibilities (
  id          uuid primary key default gen_random_uuid(),
  staff_id_a  uuid references staff_profiles(id) on delete cascade not null,
  staff_id_b  uuid references staff_profiles(id) on delete cascade not null,
  reason      text,
  severity    text not null default 'prefer_avoid'
                check (severity in ('prefer_avoid', 'never')),
  created_by  uuid references staff_profiles(id),
  created_at  timestamptz default now(),
  check (staff_id_a < staff_id_b)  -- prevents duplicate (A,B) and (B,A) entries
);


-- =============================================
-- GENERATED SCHEDULE
-- =============================================

create table scheduled_shifts (
  id                uuid primary key default gen_random_uuid(),
  monthly_config_id uuid references monthly_configs(id) on delete cascade not null,
  assigned_to       uuid references staff_profiles(id),
  date              date not null,
  start_time        time not null,
  end_time          time not null,
  status            text not null default 'draft'
                      check (status in ('draft', 'confirmed', 'available_for_swap')),
  created_at        timestamptz default now()
);


-- =============================================
-- NOTIFICATIONS
-- =============================================

create table notification_log (
  id            uuid primary key default gen_random_uuid(),
  staff_id      uuid references staff_profiles(id) on delete cascade not null,
  type          text not null,
  channel       text not null check (channel in ('email', 'sms')),
  sent_at       timestamptz default now(),
  status        text not null default 'sent' check (status in ('sent', 'failed')),
  error_message text
);


-- =============================================
-- HELPER FUNCTION (defined after staff_profiles exists)
-- =============================================

create or replace function is_admin()
returns boolean
language sql
security definer
as $$
  select exists (
    select 1 from staff_profiles
    where user_id = auth.uid()
    and role = 'admin'
  );
$$;


-- =============================================
-- ROW LEVEL SECURITY
-- =============================================

alter table staff_profiles          enable row level security;
alter table invitations              enable row level security;
alter table weekly_availability      enable row level security;
alter table availability_submissions enable row level security;
alter table availability_days        enable row level security;
alter table time_off_requests        enable row level security;
alter table monthly_configs          enable row level security;
alter table weekly_shift_templates   enable row level security;
alter table template_shifts          enable row level security;
alter table date_shift_overrides     enable row level security;
alter table override_shifts          enable row level security;
alter table staff_scheduling_rules   enable row level security;
alter table staff_incompatibilities  enable row level security;
alter table scheduled_shifts         enable row level security;
alter table notification_log         enable row level security;

-- staff_profiles
create policy "staff_profiles: own read"   on staff_profiles for select using (auth.uid() = user_id or is_admin());
create policy "staff_profiles: own update" on staff_profiles for update using (auth.uid() = user_id or is_admin());
create policy "staff_profiles: admin insert" on staff_profiles for insert with check (is_admin());

-- invitations (admin only, plus unauthenticated token lookup handled via admin client)
create policy "invitations: admin all" on invitations for all using (is_admin());

-- weekly_availability
create policy "weekly_availability: own all" on weekly_availability for all using (
  staff_id = (select id from staff_profiles where user_id = auth.uid())
  or is_admin()
);

-- availability_submissions
create policy "availability_submissions: own all" on availability_submissions for all using (
  staff_id = (select id from staff_profiles where user_id = auth.uid())
  or is_admin()
);

-- availability_days
create policy "availability_days: own all" on availability_days for all using (
  submission_id in (
    select id from availability_submissions
    where staff_id = (select id from staff_profiles where user_id = auth.uid())
  )
  or is_admin()
);

-- time_off_requests
create policy "time_off: own all"    on time_off_requests for all using (
  staff_id = (select id from staff_profiles where user_id = auth.uid())
  or is_admin()
);

-- monthly_configs (admin write, all auth read published)
create policy "monthly_configs: admin all"    on monthly_configs for all using (is_admin());
create policy "monthly_configs: staff read"   on monthly_configs for select using (status = 'published');

-- shift templates & overrides (admin write, all auth read)
create policy "weekly_shift_templates: admin all"  on weekly_shift_templates for all using (is_admin());
create policy "weekly_shift_templates: staff read" on weekly_shift_templates for select using (auth.uid() is not null);
create policy "template_shifts: admin all"         on template_shifts for all using (is_admin());
create policy "template_shifts: staff read"        on template_shifts for select using (auth.uid() is not null);
create policy "date_shift_overrides: admin all"    on date_shift_overrides for all using (is_admin());
create policy "date_shift_overrides: staff read"   on date_shift_overrides for select using (auth.uid() is not null);
create policy "override_shifts: admin all"         on override_shifts for all using (is_admin());
create policy "override_shifts: staff read"        on override_shifts for select using (auth.uid() is not null);

-- staff_scheduling_rules & incompatibilities (admin only)
create policy "staff_scheduling_rules: admin all"  on staff_scheduling_rules for all using (is_admin());
create policy "staff_incompatibilities: admin all" on staff_incompatibilities for all using (is_admin());

-- scheduled_shifts (admin full, staff read their own confirmed shifts)
create policy "scheduled_shifts: admin all"   on scheduled_shifts for all using (is_admin());
create policy "scheduled_shifts: staff read"  on scheduled_shifts for select using (
  assigned_to = (select id from staff_profiles where user_id = auth.uid())
  and status in ('confirmed', 'available_for_swap')
);

-- notification_log (admin only)
create policy "notification_log: admin all" on notification_log for all using (is_admin());
